apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: open-webui-postgres
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:16
  storage:
    size: 10Gi
    storageClass: longhorn-ssd
  bootstrap:
    initdb:
      database: openwebui
      owner: openwebui
