apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: comfyui-data
  namespace: comfyui
  labels:
    app: comfyui
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "${ .ClusterValues.storage.ssdClass }"
  resources:
    requests:
      storage: 100Gi
