apiVersion: v1
kind: Service
metadata:
  name: comfyui
  namespace: comfyui
  labels:
    app: comfyui
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8188
      targetPort: 8188
  selector:
    app: comfyui
