defaultNamespace: metallb-system

labels:
  app: metallb-config

dependsOn:
  - selector:
      matchLabels:
        app: metallb

helm:
  values:
    poolName: ipaddresspool-basic
    l2AdvName: l2advertisement-basic
    addresses:
      - "${ .ClusterValues.network.metalLbIpRange }"
