defaultNamespace: intel-device-plugins

labels:
  app: intel-device-plugins-gpu

helm:
  repo: https://intel.github.io/helm-charts
  chart: intel-device-plugins-gpu
  releaseName: intel-device-plugins
  version: 0.36.0
  values:
    sharedDevNum: "6"

dependsOn:
  - selector:
      matchLabels:
        app: intel-device-plugins-operator

# Optional: Uncomment if NFD bundle is managed via Fleet
#   - selector:
#       matchLabels:
#         app: nfd

diff:
  comparePatches:
    - apiVersion: deviceplugin.intel.com/v1
      kind: GpuDevicePlugin
      name: gpudeviceplugin-sample
      jsonPointers:
        - /spec/monitoringMode
