defaultNamespace: keda

labels:
  app: keda

helm:
  repo: https://kedacore.github.io/charts
  chart: keda
  releaseName: keda
  version: 2.16.1

diff:
  comparePatches:
    - apiVersion: admissionregistration.k8s.io/v1
      kind: ValidatingWebhookConfiguration
      name: keda-admission
      operations:
        - op: remove
          path: /webhooks/0/clientConfig/caBundle
        - op: remove
          path: /webhooks/1/clientConfig/caBundle
    - apiVersion: admissionregistration.k8s.io/v1
      kind: MutatingWebhookConfiguration
      name: keda-admission
      operations:
        - op: remove
          path: /webhooks/0/clientConfig/caBundle
        - op: remove
          path: /webhooks/1/clientConfig/caBundle

